name: otameshi

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: [self-hosted, Windows, X64, label-99]
    steps:
      - name: Command実行
        run: |
          $OutputEncoding = [System.Text.Encoding]::SJIS
          echo "あいうえおかきくけこ"
#        run: |
#          cd C:\next-fr
#          py .\auto_test_driver.py -e 2
#          echo "Hello World!"