name: otameshi

on:
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: [self-hosted, Windows, X64, label-1]
    steps:
      - name: Command実行
        run: |
          C:\ps1\b.ps1
          echo "Hello World!!!!!!!"