name: otameshi

on:
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build C
        run: |
          cd src
          gcc main.c
          ls
      - name: artifactUpload
        uses: actions/upload-artifact@v4
        with:
          name: cupload
          path: src/a.out

  job2:
    runs-on: self-hosted
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: cupload
          path: build