name: otameshi

on:
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker build
        uses: docker/setup-buildx-action@v3
        run: |
          cd Docker
          build --platform linux/amd64/v3 -t otameshi:1.0 .
          docker run --name ota otameshi:1.0
          docker cp ota:./a.out .
          docker rm ota
          docker rmi otameshi:1.0